fix(newrelic_entity): include additional ID attribute for browser app…
newrelic/terraform-provider-newrelic pull request #1018
Opened 2020-11-10 19:19 UTC by zlesnr

…lications

2020-11-10 19:24 UTC, sanderblue submitted a review, later dismissed
🐑 it

2020-11-11 20:12 UTC, ctrombley requested changes

2020-11-11 20:12 UTC, ctrombley commented on newrelic/data_source_newrelic_entity.go
> +				Description: "The browser-specific ID of the backing APM entity.",
Can we add "(only returned for Browser applications)"?

2020-11-11 21:51 UTC, sanderblue approved these changes
🦙

2020-11-11 21:52 UTC, merged