feat: Add NRQL Drop Rule support
newrelic/terraform-provider-newrelic pull request #1241
Opened 2021-02-23 20:03 UTC by paul91

Adds New Relic Terraform Provider support for managing New Relic NRQL Drop Rules (https://docs.newrelic.com/docs/accounts/accounts/data-management/drop-data-using-nerdgraph)

Feel free to suggest any nits/style changes you recommend to make it more consistent with other resources.

2021-02-23 20:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/terraform-provider-newrelic?pullRequest=1241) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/terraform-provider-newrelic?pullRequest=1241) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/terraform-provider-newrelic?pullRequest=1241) it.</sub>

2021-02-24 18:39 UTC, jthurman42 requested changes
@paul91 This is fantastic, thank you so much for the contribution!  I've made a few comments on areas where we know folks will ask / open follow-up tickets so we can get ahead of those.  Please let me know if you have any questions.

2021-02-24 18:39 UTC, jthurman42 commented on newrelic/resource_newrelic_nrql_drop_rule.go
> +	rule := created.Successes[0]
Should check for `nil` here as `created` is a pointer.

2021-02-24 18:39 UTC, jthurman42 commented on newrelic/resource_newrelic_nrql_drop_rule.go
> +	id := fmt.Sprintf("%d:%s", created.Successes[0].AccountID, rule.ID)
Since you already extract `created.Successes[0]` to `rule`, `created.Successes[0].AccountID` could be `rule.AccountID` which would read easier.

2021-02-24 18:39 UTC, jthurman42 commented on newrelic/resource_newrelic_nrql_drop_rule.go
> +	log.Printf("[INFO] Reading New Relic entity tags for entity guid %s", d.Id())
Log message for tags?

2021-02-24 18:39 UTC, jthurman42 commented on newrelic/resource_newrelic_nrql_drop_rule.go
> +func getNRQLDropRuleIDs(id string) (int, string, error) {
`parse` is probably a better name here, I was confused above when looking at the code why there were two `get` calls for the read.

2021-02-24 18:39 UTC, jthurman42 commented on newrelic/resource_newrelic_nrql_drop_rule_test.go
> +func testAccNewRelicNRQLDropRuleConfig(description string) string {
It would be good to have a test for various actions, and for `account_id` inheritance.

2021-02-24 18:39 UTC, jthurman42 commented on newrelic/resource_newrelic_nrql_drop_rule.go
> +	accountID := d.Get("account_id").(int)
`account_id` should be optional in Terraform, but it is required by the API. We get around this by trying to inherit the `account_id` from the Provider configuration.  [Here](https://github.com/newrelic/terraform-provider-newrelic/blob/master/newrelic/resource_newrelic_one_dashboard.go#L360) is a recent example.

2021-02-24 18:39 UTC, jthurman42 commented on website/docs/r/nrql_drop_rule.html.markdown
> +  * `description` - (Required) The description of the drop rule.
description is optional.  Should mention that changing it forces a new rule to be created.

2021-02-24 18:39 UTC, jthurman42 commented on website/docs/r/nrql_drop_rule.html.markdown
> +## Example Usage
A `drop_attributes` example would be great as well, and perhaps a quick sentence about what the example does.

2021-02-25 17:43 UTC, paul91 commented
@jthurman42 thanks for the thoughtful review! I believe I have addressed your feedback. Happy to make any other additional iterations as needed.

2021-03-03 15:04 UTC, paul91 commented
@jthurman42 let me know if there is anything else I can do to help move this forward. Thanks!

2021-03-03 17:58 UTC, jthurman42 commented
@paul91 Sorry I missed your updates... This looks great, please re-base / push and I'll get it merged in.

2021-03-03 19:04 UTC, jthurman42 approved these changes
Thank you for your contribution!

:shipit:

2021-03-03 19:12 UTC, merged