docs(nrql_alert_condition): removed legacy urls from doc
newrelic/terraform-provider-newrelic pull request #1536
Opened 2021-11-25 09:20 UTC by shiva-bandari

assignees: K Sandeep kumar, Shiva Bandari

2021-11-25 09:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/terraform-provider-newrelic?pullRequest=1536) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/terraform-provider-newrelic?pullRequest=1536) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/terraform-provider-newrelic?pullRequest=1536) it.</sub>

2021-11-26 08:13 UTC, kidk requested changes

2021-11-26 08:13 UTC, kidk commented on website/docs/r/nrql_alert_condition.html.markdown
> -The actual values for `policy_id` and `condition_id` can be retrieved from the following New Relic URL when viewing the NRQL alert condition you want to import:
Can you provide an alternative on how customers could find the `policy_id` and `condition_id`?

2022-03-14 16:04 UTC, mbazhlekova submitted a review, later dismissed

2022-03-17 10:19 UTC, kidk approved these changes

2022-03-17 10:46 UTC, merged