feat: awsGov cloud integration
newrelic/terraform-provider-newrelic pull request #1669
Opened 2022-02-22 12:16 UTC by sandeepkumar-kagitha

# Description

Please include a summary of the change and which issue is fixed (if relevant).

## Type of change

- [✅ ] New feature (non-breaking change which adds functionality)

## Checklist:

Please delete options that are not relevant.

- [✅] My commit message follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [✅] My code is formatted to [Go standards](https://go.dev/blog/gofmt)
- [✅] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [✅] I have added tests that prove my fix is effective or that my feature works
- [✅] New and existing unit tests pass locally with my changes. Go [here](https://github.com/newrelic/terraform-provider-newrelic#testing) for instructions on running tests locally.

## How to test this change?

Please describe how to test your changes. Include any relevant steps in the UI, HCL file(s), commands, etc

- Step 1
- Step 2
- etc

2022-03-08 10:23 UTC, kidk submitted a review, later dismissed

2022-03-14 19:10 UTC, mbazhlekova requested changes

2022-03-14 19:10 UTC, mbazhlekova commented on website/docs/r/cloud_awsGovcloud_link_account.html.markdown
> +
Can you add an Important block here to let customers know we don't have access to a AWS GovCloud account and can't properly test this resource? Take a look at [entity_tags docs](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/entity_tags) for an example

2022-03-15 11:53 UTC, ChandraIragavarapu commented
looks good

2022-03-15 15:49 UTC, mbazhlekova approved these changes

2022-03-15 15:49 UTC, merged