Oa c 38533
newrelic/terraform-provider-newrelic pull request #1969
Opened 2022-08-30 13:41 UTC by NSSPKrishna

# Description

Workloads update.
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

Please delete options that are not relevant.

- [ ] My commit message follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] My code is formatted to [Go standards](https://go.dev/blog/gofmt)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes. Go [here](https://github.com/newrelic/terraform-provider-newrelic#testing) for instructions on running tests locally.

## How to test this change?

Please describe how to test your changes. Include any relevant steps in the UI, HCL file(s), commands, etc

- Step 1
- Step 2
- etc

2022-09-30 11:34 UTC, kidk commented on newrelic/resource_newrelic_workload.go
> +						"rules": {
Change to `rule`

2022-10-06 20:39 UTC, mbazhlekova requested changes

2022-10-06 20:39 UTC, mbazhlekova commented on newrelic/resource_newrelic_workload.go
>  	accountID := d.Get("account_id").(int)
We should use `selectAccountID` function here so user doesn't have to give account ID on the resource. See example - https://github.com/newrelic/terraform-provider-newrelic/blob/main/newrelic/resource_newrelic_alert_channel.go#L281

2022-10-06 20:39 UTC, mbazhlekova commented on newrelic/resource_newrelic_workload_test.go
> +				Config: testAccNewRelicWorkloadBasicConfigOnly(rName),
We should add an update and import step for at least one of these tests. Here's an example - https://github.com/newrelic/terraform-provider-newrelic/blob/main/newrelic/resource_newrelic_alert_policy_channel_test.go#L16

2022-10-06 20:39 UTC, mbazhlekova commented on testing/newrelic.tf
> +      source  = "newrelic/newrelic"
Can remove this change

2022-10-14 08:10 UTC, kidk commented on newrelic/resource_newrelic_workload.go
>  	if err != nil {
Double err != nil check

2022-10-14 08:11 UTC, kidk commented on newrelic/resource_newrelic_workload.go
> +			if _, ok := err.(*errors.NotFound); ok {
Let's validate if this works. Delete the workload from the UI should trigger this.

2022-10-18 22:13 UTC, closed without merging