fix(src): Delete exactlyOne validation in scheme
newrelic/terraform-provider-newrelic pull request #1972
Opened 2022-08-31 15:46 UTC by silanpa

fix(src): Delete exactlyOne validation in scheme of Notification Destination

# Description

An error occurs when not supplying a block for either auth_basic or auth_token in the newrelic_notification_destination resource, even when auth is not required.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

Please delete options that are not relevant.

- [x ] My commit message follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ x] My code is formatted to [Go standards](https://go.dev/blog/gofmt)
- [ x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes. Go [here](https://github.com/newrelic/terraform-provider-newrelic#testing) for instructions on running tests locally.

## How to test this change?

Please describe how to test your changes. Include any relevant steps in the UI, HCL file(s), commands, etc

- Step 1
- Step 2
- etc

2022-08-31 15:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/terraform-provider-newrelic?pullRequest=1972) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/terraform-provider-newrelic?pullRequest=1972) before we can accept your contribution.<br/><hr/>**Ivan Tapia** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/terraform-provider-newrelic?pullRequest=1972) it.</sub>

2022-09-01 00:57 UTC, sanderblue requested changes
Hi @silanpa, thanks for the PR! Had one comment/request.

2022-09-01 12:39 UTC, silanpa commented on newrelic/resource_newrelic_notifications_destination.go
> +				Description: "Basic username and password authentication credentials.",
Hi @sanderblue . Thank you. That is exactly what I needed. I add it now!

2022-09-01 21:56 UTC, sanderblue approved these changes
Awesome, thanks! 👍

2022-09-01 22:01 UTC, sanderblue commented
@silanpa First time contributors need to sign the CLA which you can do by clicking the [yellow button in the comments to e-sign the **CLA** ](https://github.com/newrelic/terraform-provider-newrelic/pull/1972#issuecomment-1233114581)(it's just a one-time thing). Then we can merge the pull request. Thanks 🙂

2022-09-01 23:38 UTC, silanpa commented
> @silanpa First time contributors need to sign the CLA which you can do by clicking the [yellow button in the comments to e-sign the **CLA** ](https://github.com/newrelic/terraform-provider-newrelic/pull/1972#issuecomment-1233114581)(it's just a one-time thing). Then we can merge the pull request. Thanks 🙂

Ready!!

2022-09-02 06:57 UTC, merged

2022-09-02 06:58 UTC, kidk commented
Thanks @silanpa 🔥