AI Workflows and Notifications changes
newrelic/terraform-provider-newrelic pull request #1979
Opened 2022-09-05 07:18 UTC by Dani-Relic

# Description

Small changes and corrections to the docs of the Workflow, Channel, Destination resources. 

- [ ] My commit message follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] My code is formatted to [Go standards](https://go.dev/blog/gofmt)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes. Go [here](https://github.com/newrelic/terraform-provider-newrelic#testing) for instructions on running tests locally.

## How to test this change?

Please describe how to test your changes. Include any relevant steps in the UI, HCL file(s), commands, etc

- Step 1
- Step 2
- etc

2022-09-05 07:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/terraform-provider-newrelic?pullRequest=1979) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/terraform-provider-newrelic?pullRequest=1979) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/terraform-provider-newrelic?pullRequest=1979) it.</sub>

2022-09-05 07:43 UTC, shiva-bandari approved these changes

2022-09-05 09:30 UTC, lzaga-newrelic requested changes

2022-09-05 09:30 UTC, lzaga-newrelic commented on website/docs/r/notification_channel.html.markdown
> +* `status` - The status of the channel can indicate a configuration issue. The default status is DEFUALT.
This is not an outcome when you create a channel, only the id is an outcome:

<img width="739" alt="Screen Shot 2022-09-05 at 12 21 55" src="https://user-images.githubusercontent.com/69894591/188415645-efc66425-122c-4431-9250-c8e8af68e16e.png">
---
The status is a computed attribute in the schema and you're seeing it in the plan:

<img width="360" alt="Screen Shot 2022-09-05 at 12 24 42" src="https://user-images.githubusercontent.com/69894591/188416905-1a46074b-7c07-4c40-b1b1-2db2180b33b5.png">

2022-09-05 09:30 UTC, lzaga-newrelic commented on website/docs/r/notification_destination.html.markdown
> +* `status` - The status of the destination can indicate a configuration issue. The default status is DEFUALT.
same here

2022-09-05 09:42 UTC, lzaga-newrelic commented on website/docs/r/notification_channel.html.markdown
> -* `type` - (Required) The type of channel.  One of: `EMAIL`, `SERVICENOW_INCIDENTS`, `WEBHOOK`, `JIRA_CLASSIC`, `JIRA_NEXTGEN`, `PAGERDUTY_ACCOUNT_INTEGRATION` or `PAGERDUTY_SERVICE_INTEGRATION`.
This also needs to be removed from the available types in the resource file

2022-09-07 08:03 UTC, closed without merging

2022-09-11 08:50 UTC, lzaga-newrelic commented
This PR's changes added to [this](https://github.com/newrelic/terraform-provider-newrelic/pull/1990) PR.