NR-47020
newrelic/terraform-provider-newrelic pull request #2001
Opened 2022-09-13 14:28 UTC by NSSPKrishna

# Description
Made JAVASCRIPT as default to the script_language field in simple browser and script browser monitors
Please include a summary of the change and which issue is fixed (if relevant).

Fixes # (issue)
https://github.com/newrelic/terraform-provider-newrelic/issues/1977
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

## Checklist:

Please delete options that are not relevant.

- [ ] My commit message follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] My code is formatted to [Go standards](https://go.dev/blog/gofmt)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes. Go [here](https://github.com/newrelic/terraform-provider-newrelic#testing) for instructions on running tests locally.

## How to test this change?

Please describe how to test your changes. Include any relevant steps in the UI, HCL file(s), commands, etc
script_language field in browser monitors can be optional.

2022-09-13 14:53 UTC, kidk approved these changes

2022-09-13 14:54 UTC, kidk requested changes
Failing tests

2022-09-15 08:49 UTC, kidk approved these changes

2022-09-19 20:48 UTC, mbazhlekova approved these changes
Looks good to me! 🚀

2022-09-19 21:01 UTC, NSSPKrishna commented
> Looks good to me! 🚀

👍

2022-09-21 14:39 UTC, merged